/**
 * generate-shops.mjs
 *
 * קרא את כל הלוגואים מ-public/logos/ וצור src/shops-data.ts אוטומטית.
 *
 * שימוש:
 *   node scripts/generate-shops.mjs
 *
 * כל קובץ תמונה = חנות אחת.
 * שם הקובץ הופך לשם העסק (bloom-beauty.png → Bloom Beauty).
 * לאחר יצירת הקובץ, ערוך את src/shops-data.ts כדי להוסיף
 * giftName ו-giftDescription לכל חנות.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOGOS_DIR = path.resolve(__dirname, "../public/logos");
const OUT_FILE  = path.resolve(__dirname, "../src/shops-data.ts");
const IMAGE_EXT = /\.(png|jpg|jpeg|webp|svg|gif)$/i;

// ─── Helper: "bloom-beauty" → "Bloom Beauty" ─────────────────────────────────
function toTitle(filename) {
  return filename
    .replace(IMAGE_EXT, "")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, c => c.toUpperCase());
}

// ─── Read existing file to preserve manual edits ─────────────────────────────
let existing = {};
if (fs.existsSync(OUT_FILE)) {
  const src = fs.readFileSync(OUT_FILE, "utf-8");
  // Extract shops array with a simple JSON parse trick:
  // look for the exported array and eval it (safe — it's our own generated file)
  const match = src.match(/\/\/ BEGIN_SHOPS([\s\S]*?)\/\/ END_SHOPS/);
  if (match) {
    try {
      // Replace TypeScript syntax with valid JSON to parse
      const jsonLike = match[1]
        .replace(/\/\/.*$/gm, "")       // strip line comments
        .replace(/,\s*([}\]])/g, "$1"); // trailing commas
      const arr = eval("(" + jsonLike + ")"); // eslint-disable-line no-eval
      for (const shop of arr) {
        existing[shop.id] = shop;
      }
    } catch {
      // parse failed — start fresh for that entry
    }
  }
}

// ─── Read logos directory ─────────────────────────────────────────────────────
if (!fs.existsSync(LOGOS_DIR)) {
  console.error(`תיקייה לא נמצאה: ${LOGOS_DIR}`);
  process.exit(1);
}

const files = fs.readdirSync(LOGOS_DIR)
  .filter(f => IMAGE_EXT.test(f))
  .sort();

if (files.length === 0) {
  console.warn("לא נמצאו קבצי תמונה ב-public/logos/");
  process.exit(0);
}

// ─── Build shops array ────────────────────────────────────────────────────────
const shops = files.map((file, i) => {
  const id      = `shop-${i + 1}`;
  const bName   = toTitle(file);
  const prev    = existing[id] || {};
  return {
    id,
    fairId:          "main_fair",
    businessId:      `biz-${i + 1}`,
    businessName:    prev.businessName    || bName,
    giftName:        prev.giftName        || `מתנה מ-${bName}`,
    giftDescription: prev.giftDescription || `תיאור המתנה של ${bName} — ערוך ב-src/shops-data.ts`,
    giftImageUrl:    prev.giftImageUrl    || `https://picsum.photos/seed/giftfair${i + 1}/600/360`,
    logoUrl:         `/logos/${file}`,
    leadsCount:      0,
  };
});

// ─── Write output ─────────────────────────────────────────────────────────────
const lines = shops.map(s => `  {
    id: "${s.id}",
    fairId: "${s.fairId}",
    businessId: "${s.businessId}",
    businessName: "${s.businessName}",
    giftName: "${s.giftName}",
    giftDescription: "${s.giftDescription}",
    giftImageUrl: "${s.giftImageUrl}",
    logoUrl: "${s.logoUrl}",
    leadsCount: ${s.leadsCount},
  }`).join(",\n");

const output = `// THIS FILE IS AUTO-GENERATED by scripts/generate-shops.mjs
// Run: node scripts/generate-shops.mjs
// After generating, you can edit giftName / giftDescription / giftImageUrl manually —
// the next run will preserve your edits.

import type { Shop } from "./types";

const SHOPS: Shop[] = [
// BEGIN_SHOPS
${lines},
// END_SHOPS
];

export default SHOPS;
`;

fs.writeFileSync(OUT_FILE, output, "utf-8");
console.log(`✅ נוצרו ${shops.length} חנויות → src/shops-data.ts`);
shops.forEach(s => console.log(`   • ${s.businessName}  (${s.logoUrl})`));
